spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  #    sql-script-encoding: UTF-8
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
assm:
  app:
    jwtSecret: jwtAssmSecretKey
    jwtExpiration: 86400